name: Build Daikin Downloader EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/report_downloaders/daikin_downloader/src/inspection_report/download_inspection_report.py'
      - 'apps/report_downloaders/daikin_downloader/src/common/auth_code_fetcher.py'
      - 'common_utils/file_processing/unzip_files.py'
      - 'requirements.txt'

jobs:
  build:
    name: Build exe on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --paths . --hidden-import="selenium.webdriver.chrome.service" --hidden-import="selenium.webdriver.chrome.webdriver" --name Daikin_Inspection_Report_Downloader apps/report_downloaders/daikin_downloader/src/inspection_report/download_inspection_report.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: Daikin_Inspection_Report_Downloader_exe
          path: dist/Daikin_Inspection_Report_Downloader.exe
